# Generated by Django 2.0.6 on 2018-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
