# Generated by Django 2.0.6 on 2018-07-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180710_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='signed_in',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
